### ISSUE TITLE
Update docs to clarify query isn't required

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-docs-user#80]
"query: A non-empty query expression"

Won't be required after https://github.com/lightblue-platform/lightblue-core/pull/432 is merged

**Comment by bserdar** [comment]
Where is this? I can't find this phrase anywhere.

**Comment by jewzaam** [comment]
It's in the lightblue-docs-specs module, not this one.

**Comment by jewzaam** [comment]
https://github.com/lightblue-platform/lightblue-docs-specs/issues/26
