### ISSUE TITLE
Document case insensitive index with unique true

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-docs-user#91]
@BVulaj fyi, was internal email discussion about this today.  Would be good to document if / how unique case insensitive index works.  I assume the index on the hidden field would just have the unique attribute set true.

**Comment by BVulaj** [comment]
@jewzaam I can document this. For the time being, the way LB understands CI indexes, it treats them like a completely separate field/index than non CI ones.

**Comment by jewzaam** [comment]
A unique case insensitive index will work?  Just wanted to be sure of
that.  I assumed it would, but wasn't 100% sure

**Comment by BVulaj** [comment]
Definitely should.  As far as LB cares, with a Mongo Controller, the below indexes are essentially the same:

```
    {
        "fields": [
            {
                "field": "fieldName",
                "dir":"$asc",
                "caseInsensitive": true
            },
            ...
        ],
        "name": "indexName",
        "unique": true
    }
```

```
    {
        "fields": [
            {
                "field": "@mongoHidden.fieldName",
                "dir":"$asc"            },
            ...
        ],
        "name": "indexName",
        "unique": true
    }
```

**Comment by BVulaj** [comment]
@jewzaam https://github.com/lightblue-platform/lightblue-docs-user/pull/92
